# Alvin Truong
# 4/22/2024

name0= input("Please enter a name:")
name1 = input("Please enter a name:")
name2 = input("Please enter a name:")
name3 = input("Please enter a name:")
name4 = input("Please enter a name:")
name5 = input("Please enter a name:")
name6 = input("Please enter a name:")
name7 = input("Please enter a name:")
name7 = input("Please enter a name:")
name8 = input("Please enter a name:")
name9 = input("Please enter a name:")
name10 = input("Please enter a name:")
name11 = input("Please enter a name:")
name12 = input("Please enter a name:")
name13 = input("Please enter a name:")
name14=input("Please enter a name:")
name15=input("Please enter a name:")
name16=input("Please enter a name:")
name17=input("Please enter a name:")
name18=input("Please enter a name:")
name19=input("Please enter a name:")
name20=input("Please enter a name:")
print(f"Here are the names that you listed: {name0}")
print(f"{name1}")
print(f"{name2}")
print(f"{name3}")
print(f"{name4}")
print(f"{name5}")
print(f"{name6}")
print(f"{name7}")
print(f"{name8}")
print(f"{name9}")
print(f"{name10}")
print(f"{name11}")
print(f"{name12}")
print(f"{name13}")
print(f"{name14}")
print(f"{name15}")
print(f"{name16}")
print(f"{name17}")
print(f"{name18}")
print(f"{name19}")
print(f"{name20}")